---
- name: Handy Ansible Logic
  gather_facts: false
  hosts: localhost
  vars:
    var_one: 2
    var_two: 2
    var_three: 3
  tasks:

  - name: Omit when not 1
    set_fact:
      output:
        param_a: "{{ var_two if var_one == 1 else omit }}"

  - name: Print Output
    debug: 
      var: output
